create table _user
(
    id         bigint generated by default as identity,
    full_name       varchar(255) not null,
    email      varchar(100) not null unique,
    phone      varchar(25)  not null,
    birth_date date         not null,
    user_type  varchar(255) not null check (user_type in ('ADMIN', 'EDITOR', 'VIEWER')),

    primary key (id)
);